### ISSUE TITLE
several small bugs

### ISSUE THREAD

**Issue by initzhang** [jadadong/GNS#1]
1. in `GNS_yelp_amazon.py`, the profiler will initialize and start several times if the `num_epoch != 1` 
https://github.com/jadadong/GNS/blob/7ec9e9ac04c6569798518a8e3a3488e6c9043deb/graphsage/GNS_yelp_amazon.py#L428-L433

2. arguments error for code below, I guess a max-fanout [60,60,60] is missing?
https://github.com/jadadong/GNS/blob/7ec9e9ac04c6569798518a8e3a3488e6c9043deb/graphsage/GNS_yelp_amazon.py#L518-L519

3. just a suggestion: maybe we can check the existence of dir "./results1" or provide a `results_path` in the argparser? 
https://github.com/jadadong/GNS/blob/7ec9e9ac04c6569798518a8e3a3488e6c9043deb/graphsage/GNS_yelp_amazon.py#L567

4. after fix the bugs mentioned above, the program ended with an Exception. But all results(logs and pictures) are saved, so maybe this is not important?
```
Using backend: pytorch                                                                                                              
loading graph                                                                                                                                
processing graph                                                                                                                             
Pack graph                                                                                                                                   
get cache sampling probability                                                                                                               
create the model                                                                                                                             
/home/data/xzhanggb/envs/miniconda3/envs/gns/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and w
ill be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrec
t rounding for negative values.                                                                                                              
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='fl
oor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)                                                                 
  return torch.floor_divide(self, other)                                                                                                     
start training                                                                                                                               
/home/data/xzhanggb/envs/miniconda3/envs/gns/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)                                                                                                                         
/home/data/xzhanggb/envs/miniconda3/envs/gns/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountere
d in double_scalars                                                                                                                          
  ret = ret.dtype.type(ret / rcount)                                                                                                         
Epoch 00000 | Step 00000 | Loss 1.0434 | Train Acc 0.1505 | Speed (samples/sec) nan | GPU 167.2 MiB                                          
Epoch 00000 | Step 00100 | Loss 0.1851 | Train Acc 0.4962 | Speed (samples/sec) 31462.7002 | GPU 210.5 MiB                                   
Epoch 00000 | Step 00200 | Loss 0.1794 | Train Acc 0.5803 | Speed (samples/sec) 32311.8589 | GPU 219.1 MiB                                   
Epoch 00000 | Step 00300 | Loss 0.1719 | Train Acc 0.5919 | Speed (samples/sec) 31085.2463 | GPU 219.1 MiB                                   
Epoch 00000 | Step 00400 | Loss 0.1670 | Train Acc 0.5874 | Speed (samples/sec) 31076.3003 | GPU 219.1 MiB                                   
Epoch 00000 | Step 00500 | Loss 0.1627 | Train Acc 0.5765 | Speed (samples/sec) 30894.4708 | GPU 219.1 MiB                                   
Epoch Time(s): 19.5753                                                                                                                       
Epoch 00001 | Step 00000 | Loss 0.1696 | Train Acc 0.5864 | Speed (samples/sec) 30803.0536 | GPU 219.5 MiB                                   
Epoch 00001 | Step 00100 | Loss 0.1605 | Train Acc 0.6020 | Speed (samples/sec) 30148.8415 | GPU 219.5 MiB                                   
Epoch 00001 | Step 00200 | Loss 0.1633 | Train Acc 0.5847 | Speed (samples/sec) 29517.9529 | GPU 219.5 MiB                                   
Epoch 00001 | Step 00300 | Loss 0.1599 | Train Acc 0.5800 | Speed (samples/sec) 28822.6234 | GPU 219.5 MiB                                   
Epoch 00001 | Step 00400 | Loss 0.1579 | Train Acc 0.6054 | Speed (samples/sec) 28289.1415 | GPU 219.5 MiB                                   
Epoch 00001 | Step 00500 | Loss 0.1553 | Train Acc 0.6036 | Speed (samples/sec) 27906.0660 | GPU 219.5 MiB                                   
Epoch Time(s): 22.8442                                                                                                                       
Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7ff30db62950>                                                
Traceback (most recent call last):                                                                                                           
  File "/home/data/xzhanggb/envs/miniconda3/envs/gns/lib/python3.7/weakref.py", line 356, in remove                                          
  File "/home/data/xzhanggb/envs/miniconda3/envs/gns/lib/python3.7/site-packages/pyinstrument/stack_sampler.py", line 137, in _sample        
  File "/home/data/xzhanggb/envs/miniconda3/envs/gns/lib/python3.7/site-packages/pyinstrument/stack_sampler.py", line 189, in build_call_stac
k                                                                                                                                            
TypeError: 'NoneType' object is not callable
```

**Comment by initzhang** [comment]
@zheng-da

**Comment by zheng-da** [comment]
there was no error if you don't fix them?

**Comment by initzhang** [comment]
sorry my mistake, I just found out that there is a bug when compiling the specific dgl version.
